use_frameworks!

target 'frameworktest_Example' do
  pod 'frameworktest', :path => '../'

  target 'frameworktest_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
